//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSB100UserProfileWebSite.ProfileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/TSB100UserProfileService")]
    [System.SerializableAttribute()]
    public partial class UserType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TSB100UserProfileWebSite.ProfileServiceReference.AccountStatus[] AccountStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonalCodeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Security.Policy.Url PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TSB100UserProfileWebSite.ProfileServiceReference.Review[] ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TSB100UserProfileWebSite.ProfileServiceReference.AccountStatus[] AccountStatus {
            get {
                return this.AccountStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountStatusField, value) != true)) {
                    this.AccountStatusField = value;
                    this.RaisePropertyChanged("AccountStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonalCodeNumber {
            get {
                return this.PersonalCodeNumberField;
            }
            set {
                if ((this.PersonalCodeNumberField.Equals(value) != true)) {
                    this.PersonalCodeNumberField = value;
                    this.RaisePropertyChanged("PersonalCodeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phonenumber {
            get {
                return this.PhonenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonenumberField, value) != true)) {
                    this.PhonenumberField = value;
                    this.RaisePropertyChanged("Phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Security.Policy.Url Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TSB100UserProfileWebSite.ProfileServiceReference.Review[] Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="URLString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class URLString : TSB100UserProfileWebSite.ProfileServiceReference.SiteString {
        
        private TSB100UserProfileWebSite.ProfileServiceReference.DirectoryString m_directoryField;
        
        private string m_fullurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_isUncShareField;
        
        private TSB100UserProfileWebSite.ProfileServiceReference.LocalSiteString m_localSiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_parseDeferredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool m_parsedOriginalField;
        
        private int m_portField;
        
        private string m_protocolField;
        
        private TSB100UserProfileWebSite.ProfileServiceReference.SiteString m_siteStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_urlOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string m_userpassField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TSB100UserProfileWebSite.ProfileServiceReference.DirectoryString m_directory {
            get {
                return this.m_directoryField;
            }
            set {
                if ((object.ReferenceEquals(this.m_directoryField, value) != true)) {
                    this.m_directoryField = value;
                    this.RaisePropertyChanged("m_directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_fullurl {
            get {
                return this.m_fullurlField;
            }
            set {
                if ((object.ReferenceEquals(this.m_fullurlField, value) != true)) {
                    this.m_fullurlField = value;
                    this.RaisePropertyChanged("m_fullurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_isUncShare {
            get {
                return this.m_isUncShareField;
            }
            set {
                if ((this.m_isUncShareField.Equals(value) != true)) {
                    this.m_isUncShareField = value;
                    this.RaisePropertyChanged("m_isUncShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TSB100UserProfileWebSite.ProfileServiceReference.LocalSiteString m_localSite {
            get {
                return this.m_localSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_localSiteField, value) != true)) {
                    this.m_localSiteField = value;
                    this.RaisePropertyChanged("m_localSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_parseDeferred {
            get {
                return this.m_parseDeferredField;
            }
            set {
                if ((this.m_parseDeferredField.Equals(value) != true)) {
                    this.m_parseDeferredField = value;
                    this.RaisePropertyChanged("m_parseDeferred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool m_parsedOriginal {
            get {
                return this.m_parsedOriginalField;
            }
            set {
                if ((this.m_parsedOriginalField.Equals(value) != true)) {
                    this.m_parsedOriginalField = value;
                    this.RaisePropertyChanged("m_parsedOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_port {
            get {
                return this.m_portField;
            }
            set {
                if ((this.m_portField.Equals(value) != true)) {
                    this.m_portField = value;
                    this.RaisePropertyChanged("m_port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_protocol {
            get {
                return this.m_protocolField;
            }
            set {
                if ((object.ReferenceEquals(this.m_protocolField, value) != true)) {
                    this.m_protocolField = value;
                    this.RaisePropertyChanged("m_protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TSB100UserProfileWebSite.ProfileServiceReference.SiteString m_siteString {
            get {
                return this.m_siteStringField;
            }
            set {
                if ((object.ReferenceEquals(this.m_siteStringField, value) != true)) {
                    this.m_siteStringField = value;
                    this.RaisePropertyChanged("m_siteString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_urlOriginal {
            get {
                return this.m_urlOriginalField;
            }
            set {
                if ((object.ReferenceEquals(this.m_urlOriginalField, value) != true)) {
                    this.m_urlOriginalField = value;
                    this.RaisePropertyChanged("m_urlOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string m_userpass {
            get {
                return this.m_userpassField;
            }
            set {
                if ((object.ReferenceEquals(this.m_userpassField, value) != true)) {
                    this.m_userpassField = value;
                    this.RaisePropertyChanged("m_userpass");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatus", Namespace="http://schemas.datacontract.org/2004/07/TSB100UserProfileService")]
    [System.SerializableAttribute()]
    public partial class AccountStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/TSB100UserProfileService")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.DirectoryString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.LocalSiteString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.URLString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.UserType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.AccountStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.AccountStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.Review[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TSB100UserProfileWebSite.ProfileServiceReference.Review))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Security.Policy.Url))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Security.Policy.EvidenceBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class SiteString : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object[] m_separatedSiteField;
        
        private string m_siteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] m_separatedSite {
            get {
                return this.m_separatedSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_separatedSiteField, value) != true)) {
                    this.m_separatedSiteField = value;
                    this.RaisePropertyChanged("m_separatedSite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_site {
            get {
                return this.m_siteField;
            }
            set {
                if ((object.ReferenceEquals(this.m_siteField, value) != true)) {
                    this.m_siteField = value;
                    this.RaisePropertyChanged("m_site");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DirectoryString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class DirectoryString : TSB100UserProfileWebSite.ProfileServiceReference.SiteString {
        
        private bool m_checkForIllegalCharsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool m_checkForIllegalChars {
            get {
                return this.m_checkForIllegalCharsField;
            }
            set {
                if ((this.m_checkForIllegalCharsField.Equals(value) != true)) {
                    this.m_checkForIllegalCharsField = value;
                    this.RaisePropertyChanged("m_checkForIllegalChars");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalSiteString", Namespace="http://schemas.datacontract.org/2004/07/System.Security.Util")]
    [System.SerializableAttribute()]
    public partial class LocalSiteString : TSB100UserProfileWebSite.ProfileServiceReference.SiteString {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileServiceReference.IUserProfileService")]
    public interface IUserProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/CreateUser", ReplyAction="http://tempuri.org/IUserProfileService/CreateUserResponse")]
        string[] CreateUser(TSB100UserProfileWebSite.ProfileServiceReference.UserType newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/CreateUser", ReplyAction="http://tempuri.org/IUserProfileService/CreateUserResponse")]
        System.Threading.Tasks.Task<string[]> CreateUserAsync(TSB100UserProfileWebSite.ProfileServiceReference.UserType newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateUser", ReplyAction="http://tempuri.org/IUserProfileService/UpdateUserResponse")]
        string[] UpdateUser(TSB100UserProfileWebSite.ProfileServiceReference.UserType user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/UpdateUser", ReplyAction="http://tempuri.org/IUserProfileService/UpdateUserResponse")]
        System.Threading.Tasks.Task<string[]> UpdateUserAsync(TSB100UserProfileWebSite.ProfileServiceReference.UserType user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUser", ReplyAction="http://tempuri.org/IUserProfileService/GetUserResponse")]
        TSB100UserProfileWebSite.ProfileServiceReference.UserType GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserProfileService/GetUser", ReplyAction="http://tempuri.org/IUserProfileService/GetUserResponse")]
        System.Threading.Tasks.Task<TSB100UserProfileWebSite.ProfileServiceReference.UserType> GetUserAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserProfileServiceChannel : TSB100UserProfileWebSite.ProfileServiceReference.IUserProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserProfileServiceClient : System.ServiceModel.ClientBase<TSB100UserProfileWebSite.ProfileServiceReference.IUserProfileService>, TSB100UserProfileWebSite.ProfileServiceReference.IUserProfileService {
        
        public UserProfileServiceClient() {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] CreateUser(TSB100UserProfileWebSite.ProfileServiceReference.UserType newUser) {
            return base.Channel.CreateUser(newUser);
        }
        
        public System.Threading.Tasks.Task<string[]> CreateUserAsync(TSB100UserProfileWebSite.ProfileServiceReference.UserType newUser) {
            return base.Channel.CreateUserAsync(newUser);
        }
        
        public string[] UpdateUser(TSB100UserProfileWebSite.ProfileServiceReference.UserType user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<string[]> UpdateUserAsync(TSB100UserProfileWebSite.ProfileServiceReference.UserType user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public TSB100UserProfileWebSite.ProfileServiceReference.UserType GetUser(string username) {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<TSB100UserProfileWebSite.ProfileServiceReference.UserType> GetUserAsync(string username) {
            return base.Channel.GetUserAsync(username);
        }
    }
}
